import { useEffect, useMemo, useState, type ComponentType } from 'react';
import { motion, useMotionValue, useSpring, useTransform } from 'framer-motion';
import { useInView } from 'react-intersection-observer';
import CountUpModule from 'react-countup';
import Lenis from 'lenis';
import { gsap } from 'gsap';
import { Autoplay, Pagination } from 'swiper/modules';
import { Swiper, SwiperSlide } from 'swiper/react';
import { ArrowRight, ChevronDown, ChevronRight, Menu, MessageCircle, MoveRight, Sparkles, Star, X } from 'lucide-react';
import 'swiper/css'; import 'swiper/css/pagination';

const WA = `https://wa.me/0000000000?text=${encodeURIComponent('Hola, vi la página de DreamGlow Nally y deseo cotizar una decoración para mi evento.')}`;
// react-countup is published as CommonJS. This keeps it compatible with Vite's ESM dev server.
const CountUp = ((CountUpModule as unknown as { default?: ComponentType<{end:number;duration:number}> }).default ?? CountUpModule) as unknown as ComponentType<{end:number;duration:number}>;
const gallery = [
  {category:'cumple',src:'/fotos/dreamglow-evento-01.png',title:'Fiesta temática',type:'image'},
  {category:'cumple',src:'/fotos/dreamglow-evento-02.png',title:'Diseños con personalidad',type:'image'},
  {category:'elegante',src:'/fotos/dreamglow-evento-03.png',title:'Detalles que enamoran',type:'image'},
  {category:'baby',src:'/fotos/dreamglow-evento-04.png',title:'Momentos para celebrar',type:'image'},
  {category:'cumple',src:'/fotos/dreamglow-evento-05.png',title:'Una fiesta para soñar',type:'image'},
  {category:'elegante',src:'/fotos/dreamglow-evento-06.png',title:'Celebración con estilo',type:'image'},
  {category:'baby',src:'/fotos/dreamglow-evento-07.png',title:'Detalles que ilusionan',type:'image'},
] as const;
const services = [['✦','Cumpleaños','Escenarios felices para cada edad y estilo.'],['◌','Arcos de globos','Composiciones orgánicas que roban miradas.'],['♧','Mesas temáticas','Un rincón mágico pensado para celebrar.'],['♡','Baby showers','Dulces bienvenidas llenas de ternura.'],['✧','Fondos a medida','El marco perfecto para tus mejores fotos.'],['⌁','Detalles sorpresa','Globos personalizados para emocionar.']];

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { const { ref, inView } = useInView({ triggerOnce:true, threshold:.12 }); return <motion.div ref={ref} className={className} initial={{opacity:0,y:24}} animate={inView?{opacity:1,y:0}:{}} transition={{duration:.65,ease:[.22,1,.36,1]}}>{children}</motion.div> }
function MagneticLink({ children, className='', href=WA }: {children:React.ReactNode; className?:string; href?:string}) { const x=useMotionValue(0),y=useMotionValue(0); const sx=useSpring(x,{stiffness:180,damping:14}),sy=useSpring(y,{stiffness:180,damping:14}); return <motion.a href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer" style={{x:sx,y:sy}} className={`button ${className}`} onMouseMove={e=>{const b=e.currentTarget.getBoundingClientRect();x.set((e.clientX-b.left-b.width/2)*.14);y.set((e.clientY-b.top-b.height/2)*.18)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.a> }
function Nav(){const [open,setOpen]=useState(false); const links=['Inicio','Planes','Galería','Nosotros','Preguntas']; return <header className="nav"><a href="#inicio" className="logo"><img src="/assets/dreamglow-nally-logo.png" alt="DreamGlow Nally"/></a><nav className={open?'open':''}>{links.map(l=><a key={l} onClick={()=>setOpen(false)} href={`#${l.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}`}>{l}</a>)}<MagneticLink className="nav-button">Cotiza por WhatsApp <ArrowRight size={15}/></MagneticLink></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Abrir navegación">{open?<X/>:<Menu/>}</button></header>}
function Hero(){const x=useMotionValue(0),y=useMotionValue(0); const rx=useTransform(y,[-.5,.5],[8,-8]),ry=useTransform(x,[-.5,.5],[-9,9]); useEffect(()=>{const ctx=gsap.context(()=>gsap.to('.hero-rings',{rotation:360,duration:65,repeat:-1,ease:'none'}));return()=>ctx.revert()},[]);return <section className="hero" id="inicio" onPointerMove={e=>{x.set(e.clientX/innerWidth-.5);y.set(e.clientY/innerHeight-.5)}}><div className="noise"/><div className="hero-glow glow-a"/><div className="hero-glow glow-b"/><motion.div className="hero-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8}}><p className="kicker"><Sparkles size={14}/> Decoración con globos · <em>hecha con amor</em></p><h1>Decoraciones que hacen <span>brillar</span> tus momentos.</h1><p className="intro">Diseñamos experiencias llenas de color, magia y emoción para cumpleaños y eventos inolvidables.</p><div className="hero-actions"><MagneticLink className="primary">Cotiza tu decoración <ArrowRight size={17}/></MagneticLink><a className="quiet-link" href="#galeria">Ver nuestros trabajos <MoveRight size={17}/></a></div><div className="social-proof"><div className="mini-avatars"><i>♥</i><i>✦</i><i>☺</i></div><p><b>+250 celebraciones</b><br/>llenas de ilusión</p></div></motion.div><motion.div className="hero-scene" style={{rotateX:rx,rotateY:ry}}><div className="hero-rings" style={{zIndex:1}}/><Swiper modules={[Autoplay,Pagination]} autoplay={{delay:3600,disableOnInteraction:false}} pagination={{clickable:true}} loop style={{position:'absolute',right:'2%',top:'4%',width:400,height:455,zIndex:2,borderRadius:'190px 190px 24px 24px',overflow:'hidden',border:'9px solid white',boxShadow:'0 25px 45px rgba(70,21,84,.25)'}}>{gallery.map(item=><SwiperSlide key={item.src}><img className="h-full w-full object-cover" src={item.src} alt={item.title}/></SwiperSlide>)}</Swiper><div className="balloon rose b-one" style={{zIndex:4,right:'-8%',top:'-2%'}}/><div className="balloon purple b-two" style={{zIndex:4,left:'-3%'}}/><div className="balloon mint b-three" style={{zIndex:4,right:'-9%',bottom:'-4%'}}/><div className="balloon gold b-four" style={{zIndex:4,left:'1%',bottom:'5%'}}/><div className="star-shape" style={{zIndex:5}}>✦</div><div className="heart-shape" style={{zIndex:5}}>♡</div><motion.div className="scene-card" style={{zIndex:6}} animate={{y:[0,-10,0],rotate:[-6,-3,-6]}} transition={{duration:5,repeat:Infinity}}><small>momentos que</small><strong>ilusionan</strong><span>♡</span></motion.div></motion.div><a className="scroll-hint" href="#planes"><span>↓</span> descubre la magia</a></section>}
function Services(){return <section className="section" id="servicios"><Reveal className="heading"><p className="kicker">Lo hacemos especial</p><h2>Todo lo que imaginas,<br/><em>lo hacemos brillar.</em></h2><p>Detalles con personalidad para convertir tu idea en una celebración que se recuerda.</p></Reveal><div className="service-grid">{services.map(([icon,title,text],i)=><Reveal key={title}><article className="service-card"><div className="service-icon">{icon}</div><b>0{i+1}</b><h3>{title}</h3><p>{text}</p><span className="card-orb"/></article></Reveal>)}</div></section>}
function Process(){const steps=['Cuéntanos tu idea','Diseñamos tu propuesta','Coordinamos cada detalle','Hacemos magia'];return <section className="process"><Reveal className="heading center"><p className="kicker">Así de sencillo</p><h2>Tu idea, nuestro <em>toque mágico.</em></h2></Reveal><div className="steps">{steps.map((s,i)=><Reveal key={s}><article><b>0{i+1}</b><h3>{s}</h3><p>{['Fecha, ocasión, espacio y todo lo que sueñas.','Creamos una composición pensada para ti.','Te acompañamos para que todo fluya.','Llegamos a transformar tu celebración.'][i]}</p></article></Reveal>)}</div></section>}
function Gallery(){const [filter,setFilter]=useState('todos'),[image,setImage]=useState<number|null>(null);const shown=useMemo(()=>gallery.filter(g=>filter==='todos'||g.category===filter),[filter]);return <section className="section gallery" id="galeria"><Reveal className="gallery-title"><div><p className="kicker">Momentos DreamGlow</p><h2>Celebraciones que hablan<br/><em>por sí solas.</em></h2></div><a href="#contacto">Quiero algo así <ArrowRight size={18}/></a></Reveal><div className="filters">{[['todos','Todos'],['cumple','Cumpleaños'],['baby','Baby shower'],['elegante','Elegantes']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="gallery-grid">{shown.map(g=><motion.button key={g.src} layout initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} onClick={()=>setImage(gallery.indexOf(g))} className={`gallery-image item-${gallery.indexOf(g)}`}><img src={g.src} alt={g.title} loading="lazy"/><span>{g.title} <ArrowRight size={18}/></span></motion.button>)}</div>{image!==null&&<div className="modal" onClick={()=>setImage(null)}><button className="modal-close"><X/></button><img onClick={e=>e.stopPropagation()} src={gallery[image].src} alt={gallery[image].title}/><button className="modal-next" onClick={e=>{e.stopPropagation();setImage((image+1)%gallery.length)}}><ChevronRight/></button></div>}</section>}
function About(){const stats=[['250','eventos realizados'],['98','clientes felices'],['5','años creando']]; const {ref,inView}=useInView({triggerOnce:true,threshold:.3});return <section className="section about" id="nosotros"><Reveal><div className="about-image"><img src="/fotos/dreamglow-evento-06.png" alt="Decoración realizada por DreamGlow Nally" loading="lazy"/><div>Hecho<br/>con <em>amor</em> ♡</div></div></Reveal><Reveal><div className="about-copy"><p className="kicker">Somos DreamGlow Nally</p><h2>Más que decorar,<br/><em>creamos emoción.</em></h2><p>Transformamos ideas en escenarios llenos de magia. Cada detalle se diseña con creatividad, dedicación y mucho amor para que tu momento especial se sienta único.</p><a href="#contacto">Conoce nuestra historia <ArrowRight size={17}/></a><div ref={ref} className="stats">{stats.map(([n,l])=><div><strong>{inView&&<CountUp end={+n} duration={2}/>}+</strong><span>{l}</span></div>)}</div></div></Reveal></section>}
function Testimonials(){const testimonials=[['María Fernanda','Cumpleaños · 30 años','Quedó mucho más bonito de lo que imaginaba. Cada detalle tenía nuestra esencia y todos quedaron fascinados.'],['Valeria Ramos','Baby shower','Nally entendió exactamente la idea de mi baby shower. Fue delicado, elegante y precioso para las fotos.'],['Daniela Cruz','Celebración familiar','Puntuales, creativos y súper atentos. Convirtieron un espacio sencillo en una celebración increíble.']];return <section className="testimonials" id="testimonios"><Reveal className="heading center"><p className="kicker">Historias felices</p><h2>Quienes confiaron en <em>nuestra magia.</em></h2></Reveal><Swiper modules={[Autoplay,Pagination]} autoplay={{delay:5500,disableOnInteraction:false}} pagination={{clickable:true}} loop className="testimonials-slider">{testimonials.map(([name,type,quote])=><SwiperSlide><article><div className="stars">★★★★★</div><blockquote>“{quote}”</blockquote><footer><b>{name}</b><span>{type}</span></footer></article></SwiperSlide>)}</Swiper></section>}
function Packages(){const data: [string,string,string[]][]=[['Esencial','Para detalles bonitos',['Composición de globos','Paleta personalizada','Montaje profesional']],['Encanto','Para hacer una entrada',['Arco orgánico de globos','Panel personalizado','Detalles especiales','Montaje y desmontaje']],['DreamGlow Premium','Para soñar en grande',['Diseño integral del espacio','Escenografía y mesa temática','Elementos personalizados']]];const confetti=['#ff6fae','#a97bff','#7ed6c1','#f5c542','#ffb9d6'];return <section className="section packages" id="planes" style={{position:'relative',overflow:'hidden'}}><div aria-hidden="true" style={{position:'absolute',inset:0,pointerEvents:'none',zIndex:0}}>{Array.from({length:22},(_,i)=><motion.i key={i} style={{position:'absolute',left:`${(i*19+5)%96}%`,top:`${(i*31+8)%88}%`,width:i%3===0?9:6,height:i%3===0?9:14,background:confetti[i%confetti.length],borderRadius:i%2?'50%':'2px',opacity:.65}} animate={{y:[0,30,-12,0],rotate:[0,180,360],x:[0,i%2?10:-10,0]}} transition={{duration:4+i%4,repeat:Infinity,delay:i*.17,ease:'easeInOut'}}/>)}</div><Reveal className="heading center"><p className="kicker">Tu celebración, a tu medida</p><h2>Elige cómo quieres <em>brillar.</em></h2></Reveal><div className="package-grid" style={{position:'relative',zIndex:1}}>{data.map(([title,subtitle,items],i)=><Reveal key={title}><article className={`package ${i===1?'featured':''}`}>{i===1&&<span className="tag">Más elegido</span>}<p>{subtitle}</p><h3>{title}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul><MagneticLink className={i===1?'primary':'outline'}>Solicitar cotización</MagneticLink></article></Reveal>)}</div></section>}
function FAQ(){const qs=['¿Con cuánta anticipación debo reservar?','¿Realizan decoraciones personalizadas?','¿Puedo elegir los colores y la temática?','¿Incluyen traslado y desmontaje?'];const [open,setOpen]=useState(0);return <section className="faq section" id="preguntas"><Reveal className="faq-intro"><p className="kicker">Resolvemos tus dudas</p><h2>Preguntas frecuentes</h2><p>¿Tienes algo más en mente? Escríbenos y lo conversamos.</p><a href={WA} target="_blank" rel="noreferrer">Hablar por WhatsApp <ArrowRight size={17}/></a></Reveal><Reveal><div className="faq-list">{qs.map((q,i)=><article className={open===i?'expanded':''}><button onClick={()=>setOpen(open===i?-1:i)}>{q}<span>{open===i?'−':'+'}</span></button><motion.p initial={false} animate={{height:open===i?'auto':0,opacity:open===i?1:0}}>{i===0?'Te recomendamos reservar con al menos dos semanas de anticipación. Para fechas especiales, mientras antes mejor.':i===1?'Sí. Partimos de tu tema, colores, espacio y presupuesto para crear una propuesta única.':i===2?'Por supuesto. Tu celebración debe hablar de ti; trabajamos contigo cada elección.':'Lo coordinamos según tu ubicación y el tipo de montaje elegido.'}</motion.p></article>)}</div></Reveal></section>}
function Footer(){const districts='Los Olivos, San Martín de Porres, Independencia, Carabayllo, Puente Piedra, Santo Domingo, San Felipe';return <><section className="cta" id="contacto"><div className="cta-ball c1"/><div className="cta-ball c2"/><div className="cta-ball c3"/><Reveal><p className="kicker">Tu momento empieza aquí</p><h2>Haz que tu próxima<br/>celebración <em>brille.</em></h2><p>Cuéntanos tu idea y preparemos juntos una decoración inolvidable.</p><p style={{maxWidth:680,margin:'0 auto 28px',fontSize:12,lineHeight:1.6}}>Atendemos en: {districts}.</p><MagneticLink className="primary">Cotizar por WhatsApp <ArrowRight size={18}/></MagneticLink></Reveal></section><footer><div><img src="/assets/dreamglow-nally-logo.png" alt="DreamGlow Nally"/><p>Creamos momentos que ilusionan,<br/>un globo a la vez.</p></div><div><h3>Encuéntranos</h3><a href={WA}>WhatsApp</a><a href="#">Instagram</a><a href="#">Facebook</a><a href="#">TikTok</a></div><div><h3>Zona de atención</h3><p>{districts}</p><p>Lun — Sáb · 9am a 6pm</p></div><small>© 2026 DreamGlow Nally. Todos los derechos reservados.</small></footer><a className="whatsapp" href={WA} target="_blank" rel="noreferrer"><MessageCircle/><span>Cotiza tu evento</span></a></>}
export default function App(){useEffect(()=>{const lenis=new Lenis({lerp:.15,wheelMultiplier:.8,touchMultiplier:1});let id=0;const raf=(t:number)=>{lenis.raf(t);id=requestAnimationFrame(raf)};id=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(id);lenis.destroy()}},[]);return <><Nav/><main><Hero/><Packages/><Process/><Gallery/><section className="quote"><span>✦</span><div><p>Cada celebración merece</p><h2>un detalle que la haga<br/><em>inolvidable.</em></h2><MagneticLink className="white">Quiero una decoración especial <ArrowRight size={17}/></MagneticLink></div><span>♡</span></section><About/><FAQ/></main><Footer/></>}
